version: "3.7"

services:
    elasticsearch:
        build:
            context: elasticsearch/
            args:
                ELK_VERSION: ${ELK_VERSION}
        volumes:
            - type: bind
              source: ./elasticsearch/config/elasticsearch.yml
              target: /usr/share/elasticsearch/config/elasticsearch.yml
              read_only: true
            - type: volume
              source: elasticsearch
              target: /usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx2g -Xms1g"
            ELASTIC_PASSWORD: changeme
            # Use single node discovery in order to disable production mode and avoid bootstrap checks.
            # see: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/bootstrap-checks.html
            discovery.type: single-node
        network_mode: host

    kibana:
        build:
            context: kibana/
            args:
                ELK_VERSION: ${ELK_VERSION}
        volumes:
            - type: bind
              source: ./kibana/config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        ports:
            - "5601:5601"
        env_file:
            - kibana/kibana.env
        network_mode: host
        depends_on:
            - elasticsearch

volumes:
    elasticsearch:
